import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    signupTitle: "Create an Account, Join Us Today",
    loginTitle: "Hello, Welcome Back",
    username: "Username",
    usernameOrEmail: "Username",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    rememberMe: "Remember Me",
    forgotPassword: "Forgot Password?",
    alreadyHaveAccount: "Already Have An Account?",
    dontHaveAccount: "Don't Have An Account?",
    invalidlogin:"invalid username or password",
    firstName: 'First Name',
    lastName: 'Last Name',
    login: "Login",
    signup: "Signup",
    loginsucess: "logged in sucessfuly",
        phoneNumber: 'Phone Number',
    city: 'City',
    subCity: 'Sub-City',
    signup: 'Sign Up',
    alreadyHaveAccount: 'Already have an account?',
    login: 'Log In',
    passwordMismatch: 'Passwords do not match.',
    signupSuccess: 'Signup successful!',
    signupFail: 'Signup failed.',
    title: 'Digital Court Management System',
    logout: 'Logout',
    logoutConfirmation: 'Are you sure you want to logout?',
    welcomeMessage: 'Welcome to the Digital Court',
    introText: 'Submit your legal cases easily and track the progress online.',
    benefits: [
      'Fast and transparent case handling',
      'Secure document management',
      'Real-time case tracking',
      'User -friendly submission process',
    ],
    submitCaseTitle: 'Submit a Case',
    formInstructions: 'Fill out the form below carefully to submit your case.',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    emailLabel: 'Email',
    emailPlaceholder: 'Enter your email',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '+1234567890',
    phoneHelp: 'Include country code, e.g., +1234567890',
    dateOfIncidentLabel: 'Date of Incident',
    dateHelp: 'Select the date when the incident occurred',
    caseTypeLabel: 'Type of Case',
    caseTypes: ['Civil', 'Criminal', 'Family', 'Traffic', 'Other'],
    traffic: "Traffic",
    civil: "Civil",
    criminal: "Criminal",
    family: "Family",
    labor: "Labor",
    commercial: "Commercial",
    land: "Land",
    constitutional: "Constitutional",
    administrative: "Administrative",
    humanRights: "Human Rights",
    others: "Others",
    submittedToProcess: "Submitted to Process",
    underReview: "Under Review",
    approved: "Approved",
    rejected: "Rejected",
    inCourt: "In Court",
    awaitingDocuments: "Awaiting Documents",
    closed: "Closed",
    caseDescriptionLabel: 'Case Description',
    caseDescriptionPlaceholder: 'Describe your case in detail',
    idCardUploadLabel: 'Upload Your ID Card',
    idCardHelp: 'Accepted formats: PDF, JPG, PNG',
    fileUploadLabel: 'Upload Additional Files (optional)',
    fileUploadHelp: 'You may upload multiple files',
    agreementLabel: 'I agree to the terms and conditions',
    submitButton: 'Submit Case',
    validationError: 'Please fill all required fields and agree to terms.',
    caseSubmittedSuccess: 'Case submitted successfully!',
    submittedCasesTitle: 'Submitted Cases',
    noCases: 'No cases submitted yet.',
    footerNote: 'All rights reserved.',
    submittedAtLabel: 'Submitted at',
    fullNameDisplay: 'Full Name',
    emailDisplay: 'Email',
    phoneDisplay: 'Phone',
    deleteCaseButton: 'Delete Case',
    fileUploadedLabel: 'Uploaded Files',
    allRightsReserved: 'All rights reserved.',
  },
  am: {
    signupTitle: "መለያ ፍጠሩ ፣ ዛሬ ተቀላቅሉ",
    loginTitle: "ሰላም፣ እንኳን ደህና መጡ",
    username: "የተጠቃሚ ስም",
    usernameOrEmail: "የተጠቃሚ ስም",
    email: "ኢሜል",
    password: "የይለፍ ቃል",
    confirmPassword: "የይለፍ ቃልን ያረጋግጡ",
    rememberMe: "አስታውሰኝ",
    forgotPassword: "የይለፍ ቃል ረሱ?",
    alreadyHaveAccount: "መለያ አሎት?",
    dontHaveAccount: "መለያ የሎትም?",
    login: "ግባ",
    loginsucess:"በተሳካ ሁኔታ ገብተዋል",
    signup: "ይመዝገቡ",
    title: 'ዲጂታል ዳክሪ ስርዓት',
    logout: 'ውጣ',
    invalidlogin:'የተሳሳተ የተጠቃሚ ስም ወይም የይለፍ ቃል',
    logoutConfirmation: 'እርግጠኛ ነህ ለውጣ?',
   firstName: 'የመጀመሪያ ስም',
    lastName: 'የአባት ስም',
    phoneNumber: 'ስልክ ቁጥር',
    city: 'ከተማ',
    subCity: 'ክፍለ ከተማ',
    signup: 'ይመዝገቡ',
    alreadyHaveAccount: 'መለያ አሎት?',
    login: 'ይግቡ',
    passwordMismatch: 'የይለፍ ቃሎች አይመሳሰሉም።',
    signupSuccess: 'ምዝገባ ተሳክቷል!',
    signupFail: 'ምዝገባ አልተሳካም።',
  

    welcomeMessage: 'ወደ ዲጂታል ፍርድ አስተዳደር ስርዓት በሰላም መጡ',
    introText: 'ጉዳዮችዎን በኢንተርኔት ላይ ያስገቡ እና ሂደታቸውን ቀላል ያከታተሉ።',
    benefits: [
      'ፈጣንና ግልፅ የጉዳይ አስተዳደር',
      'ደህንነታማ የሰነድ አስተዳደር',
      'በሰዓት የጉዳይ መከታተያ',
      'ቀላል የማስገባት ሂደት',
    ],
    submitCaseTitle: 'ጉዳይ ያስገቡ',
    formInstructions: 'ጉዳይዎን ለማስገባት ቅጽውን በጥንቃቄ ይሙሉ።',
    fullNameLabel: 'ሙሉ ስም',
    fullNamePlaceholder: 'ሙሉ ስምዎን ያስገቡ',
    emailLabel: 'ኢሜይል',
    emailPlaceholder: 'ኢሜይልዎን ያስገቡ',
    phoneLabel: 'ስልክ ቁጥር',
    phonePlaceholder: '+251912345678',
    phoneHelp: 'ከአገር ኮድ ጋር ያስገቡ, ለምሳሌ +251912345678',
    dateOfIncidentLabel: 'የክስ ቀን',
    dateHelp: 'የክስ የተከሰተበትን ቀን ይምረጡ',
    caseTypeLabel: 'የክስ አይነት',
    caseTypes: ['ሲቪል', 'ወንጀል', 'ቤተሰብ', 'ትራፊክ', 'ሌሎች'],
    traffic: "ትራፊክ ጉዳይ",
    civil: "ሕገወጥ ጉዳይ",
    criminal: "ወንጀል ጉዳይ",
    family: "የቤተሰብ ጉዳይ",
    labor: "የሥራ አስፈፃሚ ጉዳይ",
    commercial: "ንግድ ጉዳይ",
    land: "የመሬት ጉዳይ",
    constitutional: "ሕገ መንግስት ጉዳይ",
    administrative: "አስተዳደራዊ ጉዳይ",
    humanRights: "የሰብዓዊ መብት ጉዳይ",
    others: "ሌሎች",
    submittedToProcess: "ለሂደት ተገብሟል",
    underReview: "በእይታ ላይ ነው",
    approved: "ተፅዕኖ ተሰጥቷል",
    rejected: "ተተውቷል",
    inCourt: "በፍርድ ቤት ላይ ነው",
    awaitingDocuments: "ሰነዶችን በመጠባበቅ ላይ ነው",
    closed: "ዝግ ተደርጓል",
    caseDescriptionLabel: 'የክስ መግለጫ',
    caseDescriptionPlaceholder: 'ክስዎን በተለይ ያስረዱ',
    idCardUploadLabel: 'የመታወቂያ ካርድዎን ያስገቡ',
    idCardHelp: 'ተቀባይነት ያላቸው ፎርማቶች፡ PDF, JPG, PNG',
    fileUploadLabel: 'ተጨማሪ ሰነዶች ያስገቡ (አማራጭ)',
    fileUploadHelp: 'ብዙ ሰነዶች ማስገባት ይችላሉ',
    agreementLabel: 'የህግ ሁኔታዎችን እቅድ እላለሁ',
    submitButton: 'ጉዳይ አስገባ',
    validationError: 'እባክዎ እያስፈለጉትን ሁሉ ይሙሉ እና ህግ ውሎችን ይቀበሉ።',
    caseSubmittedSuccess: 'ጉዳይ በተሳካ ሁኔታ ተሰጥቷል!',
    submittedCasesTitle: 'ተሰጥተው ያሉ ጉዳዮች',
    noCases: 'እስካሁን ምንም ጉዳይ አልተሰጠም።',
    footerNote: 'ሁሉም መብቶች የተያዙ።',
    submittedAtLabel: 'ተሰጥቷል',
    fullNameDisplay: 'ሙሉ ስም',
    emailDisplay: 'ኢሜይል',
    phoneDisplay: 'ስልክ',
    deleteCaseButton: 'ክስ አስወግድ',
    fileUploadedLabel: 'የተሰቀለ ፋይሎች',
    allRightsReserved: 'መሥሪያ መብቶች በሙሉ የተጠበቁ ናቸው。',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage(prev => (prev === 'en' ? 'am' : 'en'));
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
